/// A pair of (phrase, selectivity)
///
/// The selectivity determines the probability with which the phrase
/// appears in a random distribution. Here 0.5 is 50%, 0.1 is 10% and
/// so on...
pub(crate) const SELECTIVITY_PHRASES: &[(&str, f64)] = &[
    ("concurrency", 0.20),
    ("runtime", 0.10),
    ("indexing", 0.05),
    ("normalization", 0.01),
    ("atomics", 0.005),
    ("idempotency", 0.001),
];

pub(crate) const FILLER_WORDS: &[&str] = &[
    // Common Stop Words
    "a",
    "an",
    "and",
    "as",
    "at",
    "by",
    "for",
    "from",
    "in",
    "is",
    "it",
    "of",
    "on",
    "that",
    "the",
    "to",
    "was",
    "with",
    // Technical Nouns
    "api",
    "application",
    "architecture",
    "cache",
    "client",
    "code",
    "concurrency",
    "container",
    "data",
    "database",
    "error",
    "framework",
    "function",
    "index",
    "instance",
    "language",
    "library",
    "memory",
    "message",
    "model",
    "network",
    "pattern",
    "performance",
    "process",
    "query",
    "queue",
    "request",
    "response",
    "schema",
    "server",
    "service",
    "system",
    "thread",
    "transaction",
    // Technical Verbs
    "avoid",
    "build",
    "design",
    "ensure",
    "execute",
    "handle",
    "implement",
    "improve",
    "manage",
    "optimize",
    "process",
    "return",
    "scale",
    // Technical Adjectives
    "atomic",
    "concurrent",
    "distributed",
    "efficient",
    "high-performance",
    "scalable",
    "simple",
    "stateless",
];
