# .github/workflows/ci.yml

name: Rust CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Install the Rust toolchain
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # 3. Set up caching for dependencies to speed up future runs
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # 4. Check formatting
      - name: Check formatting
        run: cargo fmt -- --check

      # 5. Run Clippy (a powerful linter)
      # The "-D warnings" flag treats all warnings as errors, failing the build.
      - name: Run Clippy
        run: cargo clippy --workspace -- -D warnings

      # 6. Run tests
      - name: Run tests
        run: cargo test --workspace

      # 7. Build the project
      - name: Build project
        run: cargo build --workspace